-- Ignore pluggable databases
alter session set "_ORACLE_SCRIPT"=true;

-- Create oracle user
CREATE USER "ORACLE@EXAMPLE.COM" IDENTIFIED EXTERNALLY;
GRANT CONNECT TO "ORACLE@EXAMPLE.COM";
GRANT CREATE SESSION TO "ORACLE@EXAMPLE.COM";
